bodies: # List of named bodies
  - name: base_footprint
    pose: [0, 0, 0]
    type: dynamic
    color: [1.0, 0.64, 0.0, 1.0] # Orange hopefully
    footprints:
      - type: polygon
        points:
          [[0.513, 0.364], [0.513, -0.364], [-0.513, -0.364], [-0.513, 0.364]]
          # radius: 0.629 from (0.513**2 + 0.364**2)**(1/2)
        layers: ["all"]
        collision: true
        density: 1
        friction: 0.1
        restitution: 0
        sensor: false

plugins:
  - type: DiffDrive
    name: diff_drive
    body: base_footprint
    odom_frame_id: odom
    odom_pub: odom # topic odom is published on
    pub_rate: 10

  - type: Laser
    name: static_laser
    frame: scan_link
    topic: scan
    body: base_footprint
    broadcast_tf: true
    origin: [0.0, 0.0, 0.0]

    # Data from urdf files
    range: 30.0
    angle:
      {
        min: -1.5707963267948966,
        max: 1.5707963267948966,
        increment: 0.00436332312,
      }

    # noise_std_dev: 0.015
    # arena
    noise_std_dev: 0.0
    update_rate: 10

  - type: ModelTfPublisher
    name: tf_publisher
    publish_tf_world: false
    # exclude: ["approx_footprint"]
