bodies:  # List of named bodies
  - name: base_footprint
    pose: [0, 0, 0] 
    type: dynamic  
    color: [0.2, 0.8, 0.2, 1.0] 
    footprints:
      - type: circle
        radius: 0.27
        center: [0.0,0.0]
        layers: ["all"]
        collision: true
        density: 1
        friction: 0.1
        restitution: 0
        sensor: false
      

plugins:
  - type: DiffDrive 
    name: diff_drive 
    body: base_footprint
    odom_frame_id: odom
    odom_pub: odom  # topic odom is published on
    pub_rate: 10
  
  - type: Laser
    name: static_laser
    frame: laser_link
    topic: scan
    body: base_footprint
    broadcast_tf: true
    origin: [0.202, 0.0, 0.2015] # from https://github.com/ignc-research/arena-rosnav-3D/blob/main/simulator_setup/robot/tiago/pmb2_description/urdf/base/base_sensors.urdf.xacro
    range: 25.0 # from: 
    angle: {min: -1.9198600053787231, max: 1.9198600053787231, increment:  0.00533294445} # fromhttps://github.com/ignc-research/arena-rosnav-3D/blob/main/simulator_setup/robot/tiago/pmb2_description/urdf/base/base_sensors.urdf.xacro #  from 818*(1,91986 *2 /4,71239) = 666; 666/ -> alternatively from reading out the scan msg (rostopic echo scan)
    noise_std_dev: 0.0
    update_rate: 40

  - type: ModelTfPublisher
    name: tf_publisher
    publish_tf_world: false